[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/updates"
  to = "/updates.html"
  status = 200

[[redirects]]
  from = "/admin-updates"
  to = "/admin-updates.html"
  status = 200
