services:
  - type: web
    name: uday-consultancy-services
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PRIMARY_EMAIL
        value: gandlasandya@gmail.com
      - key: ALTERNATE_EMAIL
        value: ucsmitra@gmail.com
      - key: WHATSAPP_NUMBER
        value: "919912463921"
